version: '3'
services:
  iglobe-frontend:
    image: iglobe-frontend
    build: ./Mess-management-frontent
    ports:
      - 3001:3000
    depends_on:
      - iglobe-backend

  iglobe-backend:
    # container_name: spring-backend
    image: iglobe-backend
    restart: always
    build: ./Mess-management-backend
    ports:
      - 5002:5002
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=Mess
      - MYSQL_ROOT_PASSWORD=root
